import { Router } from 'express';
import authRoutes from './auth/auth.route';
import agencyRoutes from './agencies/agency.route';
import userRoutes from './users/user.route';
import roleRoutes from './roles/role.route';
import driverProfileRoutes from './driver-profiles/driver-profile.route';
import vehicleRoutes from './vehicles/vehicle.route';
import routeRoutes from './routes/route.route';
import provinceRoutes from './provinces/province.route';
import tripRoutes from './trips/trip.route';
import violationRoutes from './ai-violations/violation.route';
import driverPortalRoutes from './driver-portal/driver-portal.route';
import deviceViolationRoutes from './device-violations/device-violation.route';
import deviceGpsRoutes from './device-gps/device-gps.route';
import tripTrackingRoutes from './trip-tracking/trip-tracking.route';
import violationsInboxRoutes from './violations-inbox/violations-inbox.route';
import driverScoreRoutes from './driver-scores/driver-score.route';
import reportRoutes from './reports/reports.route';

const router = Router();
router.use('/auth', authRoutes);
router.use('/driver', driverPortalRoutes);
router.use('/device', deviceViolationRoutes);
router.use('/device', deviceGpsRoutes);
router.use('/trips', tripTrackingRoutes);
router.use('/violations', violationsInboxRoutes);
router.use('/scores', driverScoreRoutes);
router.use('/reports', reportRoutes);
router.use('/agencies/violations', violationRoutes);
router.use('/agencies/trips', tripRoutes);
router.use('/agencies', agencyRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/users', driverProfileRoutes);
router.use('/vehicles', vehicleRoutes);
router.use('/routes', routeRoutes);
router.use('/provinces', provinceRoutes);

export default router;